version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      QR_CODE_DEFAULT_URL: 'https://github.com/vidhi-thakker/qrprog.git'
      QR_CODE_DEFAULT_FILE_NAME: 'default.png'
    volumes:
      - .:/home/myuser